import { type Metadata } from "next";
import { Inter, Lora, Space_Grotesk, Syne } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import ClerkProviderWrapper from "../components/ClerkProvider";
import { CartStoreProvider } from "../providers/cart-store-provider";
import { Toaster } from "react-hot-toast";
import { getStorefrontTheme, getStorefrontThemeStyle } from "../lib/storefront-theme";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const storefrontTheme = await getStorefrontTheme();

  return (
    <html lang="en">
      <ClerkProviderWrapper>
        <CartStoreProvider>
          <body
            style={getStorefrontThemeStyle(storefrontTheme)}
            className={`${inter.variable} ${syne.variable} ${spaceGrotesk.variable} ${lora.variable} antialiased min-h-screen flex flex-col`}
          >
            <div className="mx-auto p-4 sm:max-w-xl md:max-w-2xl lg:max-w-3xl xl:max-w-6xl flex flex-col flex-1 w-full">
              <Navbar />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
            <Toaster position="top-center" />
          </body>
        </CartStoreProvider>
      </ClerkProviderWrapper>
    </html>
  );
}
